//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierCoutureGEST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int IdCommande { get; set; }
        public int ClientComm { get; set; }
        public int AdressComm { get; set; }
        public int ModelComm { get; set; }
        public string Status { get; set; }
        public System.DateTime DateCommande { get; set; }
        public System.DateTime DateLivraison { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Modeles Modeles { get; set; }
    }
}
