//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AtelierCoutureGEST.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesure
    {
        public int IdMes { get; set; }
        public int ClientMes { get; set; }
        public int ModelMes { get; set; }
        public double Tete { get; set; }
        public double Cou { get; set; }
        public double Epaule { get; set; }
        public double Bras { get; set; }
        public double Poitrine { get; set; }
        public double Hanche { get; set; }
        public double Lcorps { get; set; }
        public double CoutureExt { get; set; }
        public double Genoux { get; set; }
        public double Mollets { get; set; }
        public double Cheville { get; set; }
        public double Biceps { get; set; }
        public double Coude { get; set; }
        public int AvantBras { get; set; }
        public double PoigneCoude { get; set; }
        public double Hauteur { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Modeles Modeles { get; set; }
    }
}
