//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CoutureSewingDBModel", "fK1", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AtelierCoutureGEST.Model.Client), "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtelierCoutureGEST.Model.Commande), true)]
[assembly: EdmRelationshipAttribute("CoutureSewingDBModel", "FK1_Mesure_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AtelierCoutureGEST.Model.Client), "Mesure", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtelierCoutureGEST.Model.Mesure), true)]
[assembly: EdmRelationshipAttribute("CoutureSewingDBModel", "fK3", "Modeles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AtelierCoutureGEST.Model.Modeles), "Commande", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtelierCoutureGEST.Model.Commande), true)]
[assembly: EdmRelationshipAttribute("CoutureSewingDBModel", "FK2_Mesure_Modeles", "Modeles", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AtelierCoutureGEST.Model.Modeles), "Mesure", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AtelierCoutureGEST.Model.Mesure), true)]

#endregion

namespace AtelierCoutureGEST.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CoutureSewingDBEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CoutureSewingDBEntities1 object using the connection string found in the 'CoutureSewingDBEntities1' section of the application configuration file.
        /// </summary>
        public CoutureSewingDBEntities1() : base("name=CoutureSewingDBEntities1", "CoutureSewingDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoutureSewingDBEntities1 object.
        /// </summary>
        public CoutureSewingDBEntities1(string connectionString) : base(connectionString, "CoutureSewingDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CoutureSewingDBEntities1 object.
        /// </summary>
        public CoutureSewingDBEntities1(EntityConnection connection) : base(connection, "CoutureSewingDBEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<Client>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<Client> _Client;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Commande> Commande
        {
            get
            {
                if ((_Commande == null))
                {
                    _Commande = base.CreateObjectSet<Commande>("Commande");
                }
                return _Commande;
            }
        }
        private ObjectSet<Commande> _Commande;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Mesure> Mesure
        {
            get
            {
                if ((_Mesure == null))
                {
                    _Mesure = base.CreateObjectSet<Mesure>("Mesure");
                }
                return _Mesure;
            }
        }
        private ObjectSet<Mesure> _Mesure;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Modeles> Modeles
        {
            get
            {
                if ((_Modeles == null))
                {
                    _Modeles = base.CreateObjectSet<Modeles>("Modeles");
                }
                return _Modeles;
            }
        }
        private ObjectSet<Modeles> _Modeles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Commande EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCommande(Commande commande)
        {
            base.AddObject("Commande", commande);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Mesure EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMesure(Mesure mesure)
        {
            base.AddObject("Mesure", mesure);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Modeles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToModeles(Modeles modeles)
        {
            base.AddObject("Modeles", modeles);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoutureSewingDBModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="idClient">Initial value of the IdClient property.</param>
        /// <param name="nomClient">Initial value of the NomClient property.</param>
        /// <param name="prenomClient">Initial value of the PrenomClient property.</param>
        /// <param name="sexeClient">Initial value of the SexeClient property.</param>
        /// <param name="adressClient">Initial value of the AdressClient property.</param>
        /// <param name="cNIClient">Initial value of the CNIClient property.</param>
        /// <param name="telClient">Initial value of the TelClient property.</param>
        public static Client CreateClient(global::System.Int32 idClient, global::System.String nomClient, global::System.String prenomClient, global::System.String sexeClient, global::System.String adressClient, global::System.Int32 cNIClient, global::System.Int32 telClient)
        {
            Client client = new Client();
            client.IdClient = idClient;
            client.NomClient = nomClient;
            client.PrenomClient = prenomClient;
            client.SexeClient = sexeClient;
            client.AdressClient = adressClient;
            client.CNIClient = cNIClient;
            client.TelClient = telClient;
            return client;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdClient
        {
            get
            {
                return _IdClient;
            }
            set
            {
                if (_IdClient != value)
                {
                    OnIdClientChanging(value);
                    ReportPropertyChanging("IdClient");
                    _IdClient = StructuralObject.SetValidValue(value, "IdClient");
                    ReportPropertyChanged("IdClient");
                    OnIdClientChanged();
                }
            }
        }
        private global::System.Int32 _IdClient;
        partial void OnIdClientChanging(global::System.Int32 value);
        partial void OnIdClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomClient
        {
            get
            {
                return _NomClient;
            }
            set
            {
                OnNomClientChanging(value);
                ReportPropertyChanging("NomClient");
                _NomClient = StructuralObject.SetValidValue(value, false, "NomClient");
                ReportPropertyChanged("NomClient");
                OnNomClientChanged();
            }
        }
        private global::System.String _NomClient;
        partial void OnNomClientChanging(global::System.String value);
        partial void OnNomClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PrenomClient
        {
            get
            {
                return _PrenomClient;
            }
            set
            {
                OnPrenomClientChanging(value);
                ReportPropertyChanging("PrenomClient");
                _PrenomClient = StructuralObject.SetValidValue(value, false, "PrenomClient");
                ReportPropertyChanged("PrenomClient");
                OnPrenomClientChanged();
            }
        }
        private global::System.String _PrenomClient;
        partial void OnPrenomClientChanging(global::System.String value);
        partial void OnPrenomClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SexeClient
        {
            get
            {
                return _SexeClient;
            }
            set
            {
                OnSexeClientChanging(value);
                ReportPropertyChanging("SexeClient");
                _SexeClient = StructuralObject.SetValidValue(value, false, "SexeClient");
                ReportPropertyChanged("SexeClient");
                OnSexeClientChanged();
            }
        }
        private global::System.String _SexeClient;
        partial void OnSexeClientChanging(global::System.String value);
        partial void OnSexeClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AdressClient
        {
            get
            {
                return _AdressClient;
            }
            set
            {
                OnAdressClientChanging(value);
                ReportPropertyChanging("AdressClient");
                _AdressClient = StructuralObject.SetValidValue(value, false, "AdressClient");
                ReportPropertyChanged("AdressClient");
                OnAdressClientChanged();
            }
        }
        private global::System.String _AdressClient;
        partial void OnAdressClientChanging(global::System.String value);
        partial void OnAdressClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CNIClient
        {
            get
            {
                return _CNIClient;
            }
            set
            {
                OnCNIClientChanging(value);
                ReportPropertyChanging("CNIClient");
                _CNIClient = StructuralObject.SetValidValue(value, "CNIClient");
                ReportPropertyChanged("CNIClient");
                OnCNIClientChanged();
            }
        }
        private global::System.Int32 _CNIClient;
        partial void OnCNIClientChanging(global::System.Int32 value);
        partial void OnCNIClientChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TelClient
        {
            get
            {
                return _TelClient;
            }
            set
            {
                OnTelClientChanging(value);
                ReportPropertyChanging("TelClient");
                _TelClient = StructuralObject.SetValidValue(value, "TelClient");
                ReportPropertyChanged("TelClient");
                OnTelClientChanged();
            }
        }
        private global::System.Int32 _TelClient;
        partial void OnTelClientChanging(global::System.Int32 value);
        partial void OnTelClientChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "fK1", "Commande")]
        public EntityCollection<Commande> Commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commande>("CoutureSewingDBModel.fK1", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commande>("CoutureSewingDBModel.fK1", "Commande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "FK1_Mesure_Client", "Mesure")]
        public EntityCollection<Mesure> Mesure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mesure>("CoutureSewingDBModel.FK1_Mesure_Client", "Mesure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mesure>("CoutureSewingDBModel.FK1_Mesure_Client", "Mesure", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoutureSewingDBModel", Name="Commande")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Commande : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Commande object.
        /// </summary>
        /// <param name="idCommande">Initial value of the IdCommande property.</param>
        /// <param name="clientComm">Initial value of the ClientComm property.</param>
        /// <param name="adressComm">Initial value of the AdressComm property.</param>
        /// <param name="modelComm">Initial value of the ModelComm property.</param>
        /// <param name="status">Initial value of the Status property.</param>
        /// <param name="dateCommande">Initial value of the DateCommande property.</param>
        /// <param name="dateLivraison">Initial value of the DateLivraison property.</param>
        public static Commande CreateCommande(global::System.Int32 idCommande, global::System.Int32 clientComm, global::System.Int32 adressComm, global::System.Int32 modelComm, global::System.String status, global::System.DateTime dateCommande, global::System.DateTime dateLivraison)
        {
            Commande commande = new Commande();
            commande.IdCommande = idCommande;
            commande.ClientComm = clientComm;
            commande.AdressComm = adressComm;
            commande.ModelComm = modelComm;
            commande.Status = status;
            commande.DateCommande = dateCommande;
            commande.DateLivraison = dateLivraison;
            return commande;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdCommande
        {
            get
            {
                return _IdCommande;
            }
            set
            {
                if (_IdCommande != value)
                {
                    OnIdCommandeChanging(value);
                    ReportPropertyChanging("IdCommande");
                    _IdCommande = StructuralObject.SetValidValue(value, "IdCommande");
                    ReportPropertyChanged("IdCommande");
                    OnIdCommandeChanged();
                }
            }
        }
        private global::System.Int32 _IdCommande;
        partial void OnIdCommandeChanging(global::System.Int32 value);
        partial void OnIdCommandeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientComm
        {
            get
            {
                return _ClientComm;
            }
            set
            {
                OnClientCommChanging(value);
                ReportPropertyChanging("ClientComm");
                _ClientComm = StructuralObject.SetValidValue(value, "ClientComm");
                ReportPropertyChanged("ClientComm");
                OnClientCommChanged();
            }
        }
        private global::System.Int32 _ClientComm;
        partial void OnClientCommChanging(global::System.Int32 value);
        partial void OnClientCommChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdressComm
        {
            get
            {
                return _AdressComm;
            }
            set
            {
                OnAdressCommChanging(value);
                ReportPropertyChanging("AdressComm");
                _AdressComm = StructuralObject.SetValidValue(value, "AdressComm");
                ReportPropertyChanged("AdressComm");
                OnAdressCommChanged();
            }
        }
        private global::System.Int32 _AdressComm;
        partial void OnAdressCommChanging(global::System.Int32 value);
        partial void OnAdressCommChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelComm
        {
            get
            {
                return _ModelComm;
            }
            set
            {
                OnModelCommChanging(value);
                ReportPropertyChanging("ModelComm");
                _ModelComm = StructuralObject.SetValidValue(value, "ModelComm");
                ReportPropertyChanged("ModelComm");
                OnModelCommChanged();
            }
        }
        private global::System.Int32 _ModelComm;
        partial void OnModelCommChanging(global::System.Int32 value);
        partial void OnModelCommChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Status
        {
            get
            {
                return _Status;
            }
            set
            {
                OnStatusChanging(value);
                ReportPropertyChanging("Status");
                _Status = StructuralObject.SetValidValue(value, false, "Status");
                ReportPropertyChanged("Status");
                OnStatusChanged();
            }
        }
        private global::System.String _Status;
        partial void OnStatusChanging(global::System.String value);
        partial void OnStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateCommande
        {
            get
            {
                return _DateCommande;
            }
            set
            {
                OnDateCommandeChanging(value);
                ReportPropertyChanging("DateCommande");
                _DateCommande = StructuralObject.SetValidValue(value, "DateCommande");
                ReportPropertyChanged("DateCommande");
                OnDateCommandeChanged();
            }
        }
        private global::System.DateTime _DateCommande;
        partial void OnDateCommandeChanging(global::System.DateTime value);
        partial void OnDateCommandeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DateLivraison
        {
            get
            {
                return _DateLivraison;
            }
            set
            {
                OnDateLivraisonChanging(value);
                ReportPropertyChanging("DateLivraison");
                _DateLivraison = StructuralObject.SetValidValue(value, "DateLivraison");
                ReportPropertyChanged("DateLivraison");
                OnDateLivraisonChanged();
            }
        }
        private global::System.DateTime _DateLivraison;
        partial void OnDateLivraisonChanging(global::System.DateTime value);
        partial void OnDateLivraisonChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "fK1", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.fK1", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.fK1", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.fK1", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("CoutureSewingDBModel.fK1", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "fK3", "Modeles")]
        public Modeles Modeles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.fK3", "Modeles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.fK3", "Modeles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modeles> ModelesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.fK3", "Modeles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modeles>("CoutureSewingDBModel.fK3", "Modeles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoutureSewingDBModel", Name="Mesure")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Mesure : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Mesure object.
        /// </summary>
        /// <param name="idMes">Initial value of the IdMes property.</param>
        /// <param name="clientMes">Initial value of the ClientMes property.</param>
        /// <param name="modelMes">Initial value of the ModelMes property.</param>
        /// <param name="tete">Initial value of the Tete property.</param>
        /// <param name="cou">Initial value of the Cou property.</param>
        /// <param name="epaule">Initial value of the Epaule property.</param>
        /// <param name="bras">Initial value of the Bras property.</param>
        /// <param name="poitrine">Initial value of the Poitrine property.</param>
        /// <param name="hanche">Initial value of the Hanche property.</param>
        /// <param name="lcorps">Initial value of the Lcorps property.</param>
        /// <param name="coutureExt">Initial value of the CoutureExt property.</param>
        /// <param name="genoux">Initial value of the Genoux property.</param>
        /// <param name="mollets">Initial value of the Mollets property.</param>
        /// <param name="cheville">Initial value of the Cheville property.</param>
        /// <param name="biceps">Initial value of the Biceps property.</param>
        /// <param name="coude">Initial value of the Coude property.</param>
        /// <param name="avantBras">Initial value of the AvantBras property.</param>
        /// <param name="poigneCoude">Initial value of the PoigneCoude property.</param>
        /// <param name="hauteur">Initial value of the Hauteur property.</param>
        public static Mesure CreateMesure(global::System.Int32 idMes, global::System.Int32 clientMes, global::System.Int32 modelMes, global::System.Double tete, global::System.Double cou, global::System.Double epaule, global::System.Double bras, global::System.Double poitrine, global::System.Double hanche, global::System.Double lcorps, global::System.Double coutureExt, global::System.Double genoux, global::System.Double mollets, global::System.Double cheville, global::System.Double biceps, global::System.Double coude, global::System.Int32 avantBras, global::System.Double poigneCoude, global::System.Double hauteur)
        {
            Mesure mesure = new Mesure();
            mesure.IdMes = idMes;
            mesure.ClientMes = clientMes;
            mesure.ModelMes = modelMes;
            mesure.Tete = tete;
            mesure.Cou = cou;
            mesure.Epaule = epaule;
            mesure.Bras = bras;
            mesure.Poitrine = poitrine;
            mesure.Hanche = hanche;
            mesure.Lcorps = lcorps;
            mesure.CoutureExt = coutureExt;
            mesure.Genoux = genoux;
            mesure.Mollets = mollets;
            mesure.Cheville = cheville;
            mesure.Biceps = biceps;
            mesure.Coude = coude;
            mesure.AvantBras = avantBras;
            mesure.PoigneCoude = poigneCoude;
            mesure.Hauteur = hauteur;
            return mesure;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdMes
        {
            get
            {
                return _IdMes;
            }
            set
            {
                if (_IdMes != value)
                {
                    OnIdMesChanging(value);
                    ReportPropertyChanging("IdMes");
                    _IdMes = StructuralObject.SetValidValue(value, "IdMes");
                    ReportPropertyChanged("IdMes");
                    OnIdMesChanged();
                }
            }
        }
        private global::System.Int32 _IdMes;
        partial void OnIdMesChanging(global::System.Int32 value);
        partial void OnIdMesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClientMes
        {
            get
            {
                return _ClientMes;
            }
            set
            {
                OnClientMesChanging(value);
                ReportPropertyChanging("ClientMes");
                _ClientMes = StructuralObject.SetValidValue(value, "ClientMes");
                ReportPropertyChanged("ClientMes");
                OnClientMesChanged();
            }
        }
        private global::System.Int32 _ClientMes;
        partial void OnClientMesChanging(global::System.Int32 value);
        partial void OnClientMesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ModelMes
        {
            get
            {
                return _ModelMes;
            }
            set
            {
                OnModelMesChanging(value);
                ReportPropertyChanging("ModelMes");
                _ModelMes = StructuralObject.SetValidValue(value, "ModelMes");
                ReportPropertyChanged("ModelMes");
                OnModelMesChanged();
            }
        }
        private global::System.Int32 _ModelMes;
        partial void OnModelMesChanging(global::System.Int32 value);
        partial void OnModelMesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Tete
        {
            get
            {
                return _Tete;
            }
            set
            {
                OnTeteChanging(value);
                ReportPropertyChanging("Tete");
                _Tete = StructuralObject.SetValidValue(value, "Tete");
                ReportPropertyChanged("Tete");
                OnTeteChanged();
            }
        }
        private global::System.Double _Tete;
        partial void OnTeteChanging(global::System.Double value);
        partial void OnTeteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Cou
        {
            get
            {
                return _Cou;
            }
            set
            {
                OnCouChanging(value);
                ReportPropertyChanging("Cou");
                _Cou = StructuralObject.SetValidValue(value, "Cou");
                ReportPropertyChanged("Cou");
                OnCouChanged();
            }
        }
        private global::System.Double _Cou;
        partial void OnCouChanging(global::System.Double value);
        partial void OnCouChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Epaule
        {
            get
            {
                return _Epaule;
            }
            set
            {
                OnEpauleChanging(value);
                ReportPropertyChanging("Epaule");
                _Epaule = StructuralObject.SetValidValue(value, "Epaule");
                ReportPropertyChanged("Epaule");
                OnEpauleChanged();
            }
        }
        private global::System.Double _Epaule;
        partial void OnEpauleChanging(global::System.Double value);
        partial void OnEpauleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Bras
        {
            get
            {
                return _Bras;
            }
            set
            {
                OnBrasChanging(value);
                ReportPropertyChanging("Bras");
                _Bras = StructuralObject.SetValidValue(value, "Bras");
                ReportPropertyChanged("Bras");
                OnBrasChanged();
            }
        }
        private global::System.Double _Bras;
        partial void OnBrasChanging(global::System.Double value);
        partial void OnBrasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Poitrine
        {
            get
            {
                return _Poitrine;
            }
            set
            {
                OnPoitrineChanging(value);
                ReportPropertyChanging("Poitrine");
                _Poitrine = StructuralObject.SetValidValue(value, "Poitrine");
                ReportPropertyChanged("Poitrine");
                OnPoitrineChanged();
            }
        }
        private global::System.Double _Poitrine;
        partial void OnPoitrineChanging(global::System.Double value);
        partial void OnPoitrineChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Hanche
        {
            get
            {
                return _Hanche;
            }
            set
            {
                OnHancheChanging(value);
                ReportPropertyChanging("Hanche");
                _Hanche = StructuralObject.SetValidValue(value, "Hanche");
                ReportPropertyChanged("Hanche");
                OnHancheChanged();
            }
        }
        private global::System.Double _Hanche;
        partial void OnHancheChanging(global::System.Double value);
        partial void OnHancheChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Lcorps
        {
            get
            {
                return _Lcorps;
            }
            set
            {
                OnLcorpsChanging(value);
                ReportPropertyChanging("Lcorps");
                _Lcorps = StructuralObject.SetValidValue(value, "Lcorps");
                ReportPropertyChanged("Lcorps");
                OnLcorpsChanged();
            }
        }
        private global::System.Double _Lcorps;
        partial void OnLcorpsChanging(global::System.Double value);
        partial void OnLcorpsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double CoutureExt
        {
            get
            {
                return _CoutureExt;
            }
            set
            {
                OnCoutureExtChanging(value);
                ReportPropertyChanging("CoutureExt");
                _CoutureExt = StructuralObject.SetValidValue(value, "CoutureExt");
                ReportPropertyChanged("CoutureExt");
                OnCoutureExtChanged();
            }
        }
        private global::System.Double _CoutureExt;
        partial void OnCoutureExtChanging(global::System.Double value);
        partial void OnCoutureExtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Genoux
        {
            get
            {
                return _Genoux;
            }
            set
            {
                OnGenouxChanging(value);
                ReportPropertyChanging("Genoux");
                _Genoux = StructuralObject.SetValidValue(value, "Genoux");
                ReportPropertyChanged("Genoux");
                OnGenouxChanged();
            }
        }
        private global::System.Double _Genoux;
        partial void OnGenouxChanging(global::System.Double value);
        partial void OnGenouxChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Mollets
        {
            get
            {
                return _Mollets;
            }
            set
            {
                OnMolletsChanging(value);
                ReportPropertyChanging("Mollets");
                _Mollets = StructuralObject.SetValidValue(value, "Mollets");
                ReportPropertyChanged("Mollets");
                OnMolletsChanged();
            }
        }
        private global::System.Double _Mollets;
        partial void OnMolletsChanging(global::System.Double value);
        partial void OnMolletsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Cheville
        {
            get
            {
                return _Cheville;
            }
            set
            {
                OnChevilleChanging(value);
                ReportPropertyChanging("Cheville");
                _Cheville = StructuralObject.SetValidValue(value, "Cheville");
                ReportPropertyChanged("Cheville");
                OnChevilleChanged();
            }
        }
        private global::System.Double _Cheville;
        partial void OnChevilleChanging(global::System.Double value);
        partial void OnChevilleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Biceps
        {
            get
            {
                return _Biceps;
            }
            set
            {
                OnBicepsChanging(value);
                ReportPropertyChanging("Biceps");
                _Biceps = StructuralObject.SetValidValue(value, "Biceps");
                ReportPropertyChanged("Biceps");
                OnBicepsChanged();
            }
        }
        private global::System.Double _Biceps;
        partial void OnBicepsChanging(global::System.Double value);
        partial void OnBicepsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Coude
        {
            get
            {
                return _Coude;
            }
            set
            {
                OnCoudeChanging(value);
                ReportPropertyChanging("Coude");
                _Coude = StructuralObject.SetValidValue(value, "Coude");
                ReportPropertyChanged("Coude");
                OnCoudeChanged();
            }
        }
        private global::System.Double _Coude;
        partial void OnCoudeChanging(global::System.Double value);
        partial void OnCoudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AvantBras
        {
            get
            {
                return _AvantBras;
            }
            set
            {
                OnAvantBrasChanging(value);
                ReportPropertyChanging("AvantBras");
                _AvantBras = StructuralObject.SetValidValue(value, "AvantBras");
                ReportPropertyChanged("AvantBras");
                OnAvantBrasChanged();
            }
        }
        private global::System.Int32 _AvantBras;
        partial void OnAvantBrasChanging(global::System.Int32 value);
        partial void OnAvantBrasChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double PoigneCoude
        {
            get
            {
                return _PoigneCoude;
            }
            set
            {
                OnPoigneCoudeChanging(value);
                ReportPropertyChanging("PoigneCoude");
                _PoigneCoude = StructuralObject.SetValidValue(value, "PoigneCoude");
                ReportPropertyChanged("PoigneCoude");
                OnPoigneCoudeChanged();
            }
        }
        private global::System.Double _PoigneCoude;
        partial void OnPoigneCoudeChanging(global::System.Double value);
        partial void OnPoigneCoudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Hauteur
        {
            get
            {
                return _Hauteur;
            }
            set
            {
                OnHauteurChanging(value);
                ReportPropertyChanging("Hauteur");
                _Hauteur = StructuralObject.SetValidValue(value, "Hauteur");
                ReportPropertyChanged("Hauteur");
                OnHauteurChanged();
            }
        }
        private global::System.Double _Hauteur;
        partial void OnHauteurChanging(global::System.Double value);
        partial void OnHauteurChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "FK1_Mesure_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.FK1_Mesure_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.FK1_Mesure_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("CoutureSewingDBModel.FK1_Mesure_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("CoutureSewingDBModel.FK1_Mesure_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "FK2_Mesure_Modeles", "Modeles")]
        public Modeles Modeles
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Modeles").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Modeles").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Modeles> ModelesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Modeles>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Modeles");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Modeles>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Modeles", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CoutureSewingDBModel", Name="Modeles")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Modeles : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Modeles object.
        /// </summary>
        /// <param name="idModel">Initial value of the IdModel property.</param>
        /// <param name="nomModele">Initial value of the NomModele property.</param>
        public static Modeles CreateModeles(global::System.Int32 idModel, global::System.String nomModele)
        {
            Modeles modeles = new Modeles();
            modeles.IdModel = idModel;
            modeles.NomModele = nomModele;
            return modeles;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdModel
        {
            get
            {
                return _IdModel;
            }
            set
            {
                if (_IdModel != value)
                {
                    OnIdModelChanging(value);
                    ReportPropertyChanging("IdModel");
                    _IdModel = StructuralObject.SetValidValue(value, "IdModel");
                    ReportPropertyChanged("IdModel");
                    OnIdModelChanged();
                }
            }
        }
        private global::System.Int32 _IdModel;
        partial void OnIdModelChanging(global::System.Int32 value);
        partial void OnIdModelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NomModele
        {
            get
            {
                return _NomModele;
            }
            set
            {
                OnNomModeleChanging(value);
                ReportPropertyChanging("NomModele");
                _NomModele = StructuralObject.SetValidValue(value, false, "NomModele");
                ReportPropertyChanged("NomModele");
                OnNomModeleChanged();
            }
        }
        private global::System.String _NomModele;
        partial void OnNomModeleChanging(global::System.String value);
        partial void OnNomModeleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "fK3", "Commande")]
        public EntityCollection<Commande> Commande
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Commande>("CoutureSewingDBModel.fK3", "Commande");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Commande>("CoutureSewingDBModel.fK3", "Commande", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CoutureSewingDBModel", "FK2_Mesure_Modeles", "Mesure")]
        public EntityCollection<Mesure> Mesure
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Mesure>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Mesure");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Mesure>("CoutureSewingDBModel.FK2_Mesure_Modeles", "Mesure", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
